#include <stdio.h>
#include "ft_printf.h"
#include <locale.h>

int main(void)
{
	char	str[] = "Is this how printf works";
	int		num;
	int		neg;
	num = 42;
	neg = -42;

	ft_printf("Torrey at it again\n");
	printf("Torrey at it again\n");
	ft_printf("%%\n");
	printf("%%\n");
	ft_printf("s_spec: %s\n", str);
	printf("s_spec: %s\n", str);
	ft_printf("d_spec: %d\n", num);
	printf("d_spec: %d\n", num);
	ft_printf("x_spec: %x\n", num);
	printf("x_spec: %x\n", num);
	ft_printf("d_spec: %d\n", neg);
	printf("d_spec: %d\n", neg);
	ft_printf("x_spec: %x\n", neg);
	printf("x_spec: %x\n", neg);
	// printf("1my printf:");
	// ft_printf("% d\n", 42);
	// printf("1stdprintf:");
	// 	printf("% d\n", 42);
	// printf("2my printf:");
	// ft_printf("% d\n", -42);
	// printf("2stdprintf:");
	// 	printf("% d\n", -42);
	// printf("3my printf:");
	// ft_printf("% 5d\n", 42);
	// printf("3stdprintf:");
	// 	printf("% 5d\n", 42);
	// printf("4my printf:");
	// ft_printf("% 5d\n", -42);
	// printf("4stdprintf:");
	// 	printf("% 5d\n", -42);
	// printf("5my printf:");
	// ft_printf("% 15d\n", 42);
	// printf("5stdprintf:");
	// 	printf("% 15d\n", 42);
	// printf("6my printf:");
	// ft_printf("% 15d\n", -42);
	// printf("6stdprintf:");
	// 	printf("% 15d\n", -42);
	// printf("7my printf:");
	// ft_printf("%+d\n", 42);
	// printf("7stdprintf:");
	// 	printf("%+d\n", 42);
	// printf("8my printf:");
	// ft_printf("%+d\n", -42);
	// printf("8stdprintf:");
	// 	printf("%+d\n", -42);
	// printf("9my printf:");
	// ft_printf("%+5d\n", 42);
	// printf("9stdprintf:");
	// 	printf("%+5d\n", 42);
	// printf("10my printf:");
	// ft_printf("%+5d\n", -42);
	// printf("10stdprintf:");
	// 	printf("%+5d\n", -42);
	// printf("11my printf:");
	// ft_printf("%+15d\n", 42);
	// printf("11stdprintf:");
	// 	printf("%+15d\n", 42);
	// printf("12my printf:");
	// ft_printf("%+15d\n", -42);
	// printf("12stdprintf:");
	// 	printf("%+15d\n", -42);
	// printf("13my printf:");
	// ft_printf("%0d\n", 42);
	// printf("13stdprintf:");
	// 	printf("%0d\n", 42);
	// printf("14my printf:");
	// ft_printf("%0d\n", -42);
	// printf("14stdprintf:");
	// 	printf("%0d\n", -42);
	// printf("15my printf:");
	// ft_printf("%05d\n", 42);
	// printf("15stdprintf:");
	// 	printf("%05d\n", 42);
	// printf("16my printf:");
	// ft_printf("%05d\n", -42);
	// printf("16stdprintf:");
	// 	printf("%05d\n", -42);
	// printf("17my printf:");
	// ft_printf("%015d\n", 42);
	// printf("17stdprintf:");
	// 	printf("%015d\n", 42);
	// printf("18my printf:");
	// ft_printf("%015d\n", -42);
	// printf("18stdprintf:");
	// 	printf("%015d\n", -42);
	// printf("19my printf:");
	// ft_printf("%-d\n", 42);
	// printf("19stdprintf:");
	// 	printf("%-d\n", 42);
	// printf("20my printf:");
	// ft_printf("%-d\n", -42);
	// printf("20stdprintf:");
	// 	printf("%-d\n", -42);
	// printf("21my printf:");
	// ft_printf("%-5d\n", 42);
	// printf("21stdprintf:");
	// 	printf("%-5d\n", 42);
	// printf("22my printf:");
	// ft_printf("%-5d\n", -42);
	// printf("22stdprintf:");
	// 	printf("%-5d\n", -42);
	// printf("23my printf:");
	// ft_printf("%-15d\n", 42);
	// printf("23stdprintf:");
	// 	printf("%-15d\n", 42);
	// printf("24my printf:");
	// ft_printf("%-15d\n", -42);
	// printf("24stdprintf:");
	// 	printf("%-15d\n", -42);
	// printf("25my printf:");
	// ft_printf("%-0d\n", 42);
	// printf("25stdprintf:");
	// 	printf("%-0d\n", 42);
	// printf("26my printf:");
	// ft_printf("%-0d\n", -42);
	// printf("26stdprintf:");
	// 	printf("%-0d\n", -42);
	// printf("27my printf:");
	// ft_printf("%-05d\n", 42);
	// printf("27stdprintf:");
	// 	printf("%-05d\n", 42);
	// printf("28my printf:");
	// ft_printf("%-05d\n", -42);
	// printf("28stdprintf:");
	// 	printf("%-05d\n", -42);
	// printf("29my printf:");
	// ft_printf("%-015d\n", 42);
	// printf("29stdprintf:");
	// 	printf("%-015d\n", 42);
	// printf("30my printf:");
	// ft_printf("%-015d\n", -42);
	// printf("30stdprintf:");
	// 	printf("%-015d\n", -42);
	// printf("31my printf:");
	// ft_printf("%0-d\n", 42);
	// printf("31stdprintf:");
	// 	printf("%0-d\n", 42);
	// printf("32my printf:");
	// ft_printf("%0-d\n", -42);
	// printf("32stdprintf:");
	// 	printf("%0-d\n", -42);
	// printf("33my printf:");
	// ft_printf("%0-5d\n", 42);
	// printf("33stdprintf:");
	// 	printf("%0-5d\n", 42);
	// printf("34my printf:");
	// ft_printf("%0-5d\n", -42);
	// printf("34stdprintf:");
	// 	printf("%0-5d\n", -42);
	// printf("35my printf:");
	// ft_printf("%0-15d\n", 42);
	// printf("35stdprintf:");
	// 	printf("%0-15d\n", 42);
	// printf("36my printf:");
	// ft_printf("%0-15d\n", -42);
	// printf("36stdprintf:");
	// 	printf("%0-15d\n", -42);
	return (0);
}
